### ISSUE TITLE
Wallpaper filter

### ISSUE THREAD

**Issue by martasd** [Jomik/gnome-wallpaper-changer#3]
Hi. Would it be possible to add a filter for Wallhaven provider, for example, "nature wallpapers"?

**Comment by Jomik** [comment]
This should already be possible using the `query` setting.
Please report back if that is not the case, and we can try to solve it.
I will happily accept a PR :+1: 

I am currently not using GNOME myself, as I switched to XMonad, thus I don't actually have my extension in use.

**Comment by martasd** [comment]
Ah, yeah. That seems to be working. Thanks!
